### ISSUE TITLE
Load more data when there is not scroll on the page for large resolutions.

### ISSUE THREAD

**Issue by krishnenduroy52** [krishnenduroy52/Anime-Player#1]
# Problem: 
- Infinity Scroll unable to call loadMore function. Because there is not scroll need after First time data load. 
- https://animix.netlify.app/
![image](https://user-images.githubusercontent.com/42006435/197414226-5ecf70f7-cdc9-414b-9237-933ffb21f485.png)

**Comment by Aksa12** [comment]
Hey @krishnenduroy52, I would like to work on this issue

**Comment by krishnenduroy52** [comment]
@Aksa12 Sure, go on.

**Comment by Aksa12** [comment]
@krishnenduroy52 fixed in the linked pr
